"""
雷达图可视化模块 - 平均排名对比

本模块提供通用的雷达图（蜘蛛网图）绘图函数，用于展示多个方法在多个维度上的平均排名对比。
图表采用简洁学术风格，适用于科研论文和技术报告。

作者：Generated by Qwen Code
日期：2026 年 2 月 26 日
"""

from math import pi
import os
from matplotlib import pyplot as plt
from matplotlib.font_manager import FontProperties
import numpy as np


# ============================================================================
# 预定义颜色方案 - 低饱和度柔和配色
# ============================================================================
# 采用柔和的低饱和度颜色，避免视觉疲劳，适合学术出版
# 颜色顺序经过设计，确保在黑白打印时仍有较好的区分度
PREDEFINED_COLORS = [
    "#4A90C8",  # 柔和蓝色 - 代表主要方法
    "#7CB342",  # 柔和绿色 - 代表对比方法
    "#FFB74D",  # 柔和橙色 - 代表基线方法
    "#BA68C8",  # 柔和紫色 - 代表进阶方法
    "#F06292",  # 柔和粉色 - 代表变体方法
    "#81C784",  # 柔和浅绿 - 代表优化方法
    "#64B5F6",  # 柔和天蓝 - 代表改进方法
    "#FFD54F",  # 柔和黄色 - 代表特殊方法
]


# ============================================================================
# 默认字体大小设置 - 学术风格（统一 16pt）
# ============================================================================
# 遵循学术图表字体大小规范，确保清晰可读
TITLE_FONTSIZE = 16        # 标题字体大小
LABEL_FONTSIZE = 16        # 维度标签字体大小
TICK_FONTSIZE = 16         # 刻度标签字体大小
LEGEND_FONTSIZE = 16       # 图例字体大小


def plot_radar_chart_average_rank(
    data,
    dimensions=None,
    title="Average Rank (Lower is Better)",
    save_path=None,
    figsize=(10, 10),
    colors=None,
    line_width=2.5,
    alpha_fill=0.15,
    alpha_line=0.9,
    show_legend=True,
    legend_ncol=3,
    y_min=None,
    y_max=None,
    y_ticks=None,
    grid_alpha=0.25,
    grid_linewidth=1.5,
    radial_grid_linewidth=1.0,
    dimension_fontsize=LABEL_FONTSIZE,
    title_fontsize=TITLE_FONTSIZE,
    tick_fontsize=TICK_FONTSIZE,
    legend_fontsize=LEGEND_FONTSIZE,
    dpi=300
):
    """
    绘制雷达图（蜘蛛网图）- 用于展示多个方法在多个维度上的平均排名对比
    
    本函数采用简洁学术风格，白色背景，中心为原点向外辐射的同心圆网格线，
    使用浅灰色虚线表示。径向轴线从中心向六个维度均匀分布，使用深灰色细实线。
    不同方法使用不同颜色的线条连接各维度形成多边形，采用低饱和度的柔和配色方案。
    
    参数说明:
    ----------
    data : dict
        字典格式数据，键为方法名称，值为该方法的各维度得分列表。
        示例：{
            'Method A': [2.1, 3.5, 1.8, 2.9, 3.2, 2.5],
            'Method B': [2.8, 2.9, 2.1, 3.1, 2.7, 3.0],
            'Method C': [3.5, 2.2, 2.8, 2.4, 2.9, 2.8]
        }
        注意：排名值越小表示越好（Lower is Better）
    
    dimensions : list, optional
        维度名称列表，支持使用 '\\n' 进行多行显示。
        如果为 None，则自动生成 Dimension_1, Dimension_2, ...
        示例：[
            'Professional\\nCommunication\\nand Clarity',
            'Patient-Centered Response',
            'Clinical\\nAccuracy\\nand Safety',
            'Patient-Readiness',
            'Completeness\\nand Practical\\nApplicability'
        ]
    
    title : str, optional
        图表标题，默认为 "Average Rank (Lower is Better)"
        标题位于图表顶部居中，注明排名含义
    
    save_path : str, optional
        图片保存路径。如果为 None，则不保存，仅显示。
        如果指定路径，函数会自动创建所需的目录结构。
    
    figsize : tuple, optional
        图表尺寸（宽，高），单位为英寸，默认为 (10, 10)
        建议保持正方形比例以确保雷达图的对称性
    
    colors : list, optional
        颜色列表。如果为 None，则使用预定义的柔和配色方案。
        颜色数量应不少于方法数量。
        示例：["#4A90C8", "#7CB342", "#FFB74D", "#BA68C8"]
    
    line_width : float, optional
        线条粗细，默认为 2.5
        建议值范围：1.5 - 4.0
    
    alpha_fill : float, optional
        多边形填充色透明度，默认为 0.15
        值越小越透明，确保不遮挡网格线
        建议值范围：0.05 - 0.3
    
    alpha_line : float, optional
        线条透明度，默认为 0.9
        值越大越不透明
        建议值范围：0.7 - 1.0
    
    show_legend : bool, optional
        是否显示图例，默认为 True
    
    legend_ncol : int, optional
        图例列数，默认为 3（水平排列）
        根据方法数量调整，确保图例美观
    
    y_max : float, optional
        Y 轴最大值（排名上限）。如果为 None，则根据数据动态调整。
        对于排名数据，通常设置为维度数量或稍大。
    
    y_ticks : list, optional
        Y 轴刻度位置列表。如果为 None，则自动生成。
        示例：[1, 2, 3, 4] 或 [0, 1, 2, 3, 4]
    
    grid_alpha : float, optional
        网格线透明度，默认为 0.25
        值越小网格越淡，避免干扰数据展示

    grid_linewidth : float, optional
        同心圆网格线（虚线）粗细，默认为 1.5
        增加此值可使刻度线更清晰
        建议值范围：1.0 - 3.0

    radial_grid_linewidth : float, optional
        径向轴线（从中心辐射的实线）粗细，默认为 1.0
        增加此值可使径向轴线更明显
        建议值范围：0.5 - 2.0

    dimension_fontsize : int, optional
        维度标签字体大小，默认为 LABEL_FONTSIZE (14)
    
    title_fontsize : int, optional
        标题字体大小，默认为 TITLE_FONTSIZE (18)
    
    tick_fontsize : int, optional
        刻度标签字体大小，默认为 TICK_FONTSIZE (12)
    
    legend_fontsize : int, optional
        图例字体大小，默认为 LEGEND_FONTSIZE (14)
    
    dpi : int, optional
        保存图像时的分辨率，默认为 300
        学术出版建议使用 300 或更高
    
    返回:
    -----
    fig : matplotlib.figure.Figure
        创建的 Figure 对象
    
    ax : matplotlib.axes.Axes
        创建的 Axes 对象
    
    示例:
    -----
    >>> data = {
    ...     'Method A': [2.1, 3.5, 1.8, 2.9, 3.2, 2.5],
    ...     'Method B': [2.8, 2.9, 2.1, 3.1, 2.7, 3.0]
    ... }
    >>> dimensions = ['Dim1', 'Dim2', 'Dim3', 'Dim4', 'Dim5', 'Dim6']
    >>> fig, ax = plot_radar_chart_average_rank(data, dimensions, save_path='radar.png')
    """
    
    # ========================================================================
    # 步骤 1: 数据验证与预处理
    # ========================================================================
    
    # 检查数据是否为空
    if not data:
        raise ValueError("错误：数据不能为空，请提供至少一个方法的评分数据")
    
    # 获取第一个方法作为参考，确定维度数量
    first_method = next(iter(data))
    expected_dim_count = len(data[first_method])
    
    # 验证所有方法的维度数量是否一致
    for method, scores in data.items():
        if len(scores) != expected_dim_count:
            raise ValueError(
                f"错误：方法 '{method}' 的维度数量 ({len(scores)}) 与其他方法不一致 "
                f"(期望：{expected_dim_count})"
            )
    
    # 处理维度名称
    if dimensions is None:
        # 如果没有提供维度名称，自动生成
        dimensions = [f"Dimension_{i + 1}" for i in range(expected_dim_count)]
    else:
        if len(dimensions) != expected_dim_count:
            raise ValueError(
                f"错误：维度名称数量 ({len(dimensions)}) 与数据维度数量 ({expected_dim_count}) 不匹配"
            )
    
    # ========================================================================
    # 步骤 2: 计算雷达图角度
    # ========================================================================
    
    # 计算每个维度的角度（弧度制）
    # 雷达图是圆形，360 度均匀分配给所有维度
    angles = [n / float(expected_dim_count) * 2 * pi for n in range(expected_dim_count)]
    
    # 闭合多边形：在角度列表末尾添加第一个角度
    angles_closed = angles + angles[:1]
    
    # ========================================================================
    # 步骤 3: 创建图表和极坐标轴
    # ========================================================================
    
    # 创建图形和极坐标轴（projection='polar' 启用极坐标系统）
    fig, ax = plt.subplots(
        figsize=figsize,
        subplot_kw=dict(projection='polar'),
        dpi=100  # 显示时的 DPI
    )
    
    # ========================================================================
    # 步骤 4: 设置颜色方案
    # ========================================================================
    
    # 确定使用的颜色
    if colors is None:
        # 使用预定义颜色，根据方法数量截取
        colors = PREDEFINED_COLORS[:len(data)]
    else:
        # 如果提供的颜色不够，循环使用
        if len(colors) < len(data):
            # 扩展颜色列表
            colors = colors * ((len(data) // len(colors)) + 1)
            colors = colors[:len(data)]
    
    # ========================================================================
    # 步骤 5: 绘制每个方法的多边形
    # ========================================================================
    
    # 遍历每个方法，绘制其雷达图多边形
    for idx, (method, scores) in enumerate(data.items()):
        # 闭合数据：在末尾添加第一个分数，形成闭合多边形
        scores_closed = scores + scores[:1]
        
        # 获取当前方法的颜色
        color = colors[idx % len(colors)]
        
        # 绘制填充的多边形（面）
        ax.fill(
            angles_closed,
            scores_closed,
            color=color,
            alpha=alpha_fill,  # 高透明度，避免遮挡网格线
            zorder=1  # 底层
        )
        
        # 绘制轮廓线（边框）
        ax.plot(
            angles_closed,
            scores_closed,
            color=color,
            linewidth=line_width,
            alpha=alpha_line,
            label=method,
            zorder=2  # 在填充层之上
        )
    
    # ========================================================================
    # 步骤 6: 设置维度标签位置
    # ========================================================================

    # 设置 X 轴刻度位置（每个维度一个刻度）
    ax.set_xticks(angles)

    # 隐藏默认的 X 轴刻度标签
    ax.set_xticklabels([])

    # 手动添加维度标签，根据角度调整对齐方式
    # 确保标签始终正向可读，位于图表外围
    # 加入换行符防止文字拉宽图片
    for angle, dimension in zip(angles, dimensions):
        # 根据角度确定水平对齐方式
        if angle == 0:
            ha, va = 'left', 'center'
        elif 0 < angle < pi / 2:
            ha, va = 'left', 'bottom'
        elif angle == pi / 2:
            ha, va = 'center', 'bottom'
        elif pi / 2 < angle < pi:
            ha, va = 'right', 'bottom'
        elif angle == pi:
            ha, va = 'right', 'center'
        elif pi < angle < 3 * pi / 2:
            ha, va = 'right', 'top'
        elif angle == 3 * pi / 2:
            ha, va = 'center', 'top'
        else:  # 3*pi/2 < angle < 2*pi
            ha, va = 'left', 'top'

        # 在图表外围添加维度标签（加入换行符）
        # 使用 ax.get_ylim()[1] 获取 Y 轴上限，将标签放在 102% 的位置（更靠近圆圈）
        ax.text(
            angle,
            ax.get_ylim()[1] * 1.02,  # 更靠近圆圈
            dimension,
            horizontalalignment=ha,
            verticalalignment=va,
            fontsize=dimension_fontsize,
            fontweight='bold',
            multialignment='center',
            family='sans-serif'  # 使用无衬线字体
        )
    
    # ========================================================================
    # 步骤 7: 设置 Y 轴范围和刻度
    # ========================================================================

    # 收集所有分数值，用于确定 Y 轴范围
    all_scores = [score for scores in data.values() for score in scores]
    max_score = max(all_scores)
    min_score = min(all_scores)

    # 确定 Y 轴范围
    if y_min is None:
        y_min = 0
    if y_max is None:
        # 默认设置为 0-9 的范围
        y_max = 9

    # 设置 Y 轴范围
    ax.set_ylim(y_min, y_max)

    # 确定 Y 轴刻度位置
    if y_ticks is None:
        # 自动生成刻度：从 y_min 到 y_max 的整数
        y_ticks = list(range(int(y_min), int(y_max) + 1))

    # 设置 Y 轴刻度和标签
    ax.set_yticks(y_ticks)
    # 根据刻度值大小决定保留几位小数
    tick_labels = []
    for tick in y_ticks:
        if tick == int(tick):
            tick_labels.append(str(int(tick)))
        else:
            tick_labels.append(f'{tick:.1f}')
    ax.set_yticklabels(
        tick_labels,
        fontsize=tick_fontsize,
        family='sans-serif'
    )
    
    # ========================================================================
    # 步骤 8: 设置网格样式
    # ========================================================================

    # 设置网格线样式：浅灰色虚线，低透明度
    # 同心圆网格线（虚线）- 用于显示刻度
    ax.grid(
        True,
        linestyle='--',          # 虚线
        linewidth=grid_linewidth,  # 加粗的线宽，使刻度更清晰
        color='#999999',         # 中灰色（比之前稍深）
        alpha=grid_alpha         # 低透明度
    )

    # 设置径向轴线（从中心辐射的线）
    # 这些线已经由极坐标系统自动绘制，我们设置其样式
    for spine in ax.spines.values():
        spine.set_visible(False)  # 隐藏边框

    # 设置径向网格线的样式（从中心向外的轴线）
    ax.xaxis.grid(
        True,
        linestyle='-',              # 实线
        linewidth=radial_grid_linewidth,  # 加粗的线宽
        color='#555555',            # 深灰色（比之前稍深）
        alpha=0.5                   # 稍高的透明度，使轴线更可见
    )
    
    # ========================================================================
    # 步骤 9: 设置标题
    # ========================================================================
    
    if title:
        # 添加标题，位于图表顶部居中
        # pad 参数控制标题与图表的距离
        ax.set_title(
            title,
            size=title_fontsize,
            fontweight='bold',
            pad=30,  # 标题与图表的距离
            family='sans-serif'
        )
    
    # ========================================================================
    # 步骤 10: 设置图例
    # ========================================================================
    
    if show_legend:
        # 图例位于图表底部，水平排列，无边框
        # bbox_to_anchor 控制图例位置：(0.5, 1.05) 表示底部居中
        plt.legend(
            loc='upper center',           # 图例锚点位置
            bbox_to_anchor=(0.5, -0.15),  # 图例相对于轴的偏移
            fontsize=legend_fontsize,
            frameon=False,                # 无边框
            ncol=legend_ncol,             # 列数，水平排列
            labelspacing=0.3,             # 行间距
            columnspacing=1.5,            # 列间距
            handletextpad=0.5             # 图标与文字的间距
        )
    
    # ========================================================================
    # 步骤 11: 调整布局并保存/显示
    # ========================================================================
    
    # 自动调整布局，确保标签和图例不被裁剪
    plt.tight_layout()
    
    # 保存或显示图表
    if save_path:
        # 确保目录存在
        save_dir = os.path.dirname(save_path)
        if save_dir and not os.path.exists(save_dir):
            os.makedirs(save_dir, exist_ok=True)
        
        # 保存高分辨率 TIF 图片
        plt.savefig(
            save_path,
            dpi=300,
            bbox_inches='tight',  # 紧凑边界
            facecolor='white',     # 白色背景
            format='tiff'
        )
        print(f"雷达图已保存至：{os.path.abspath(save_path)}")
        
        # 关闭图形，释放内存
        plt.close()
    else:
        # 显示图形
        plt.show()
    
    return fig, ax


def generate_test_data(
    n_methods=5,
    n_dimensions=6,
    score_range=(1, 4),
    method_prefix="Method",
    random_seed=None
):
    """
    生成随机测试数据，用于演示和测试雷达图功能
    
    参数:
    -----
    n_methods : int, optional
        方法数量，默认为 5
    
    n_dimensions : int, optional
        维度数量，默认为 6
    
    score_range : tuple, optional
        分数范围 (最小值，最大值)，默认为 (1, 4)
    
    method_prefix : str, optional
        方法名称前缀，默认为 "Method"
    
    random_seed : int, optional
        随机种子，用于复现结果
    
    返回:
    -----
    data : dict
        生成的测试数据字典
    """
    
    # 设置随机种子（如果提供）
    if random_seed is not None:
        np.random.seed(random_seed)
    
    # 生成数据
    data = {}
    min_score, max_score = score_range
    
    for i in range(n_methods):
        method_name = f"{method_prefix} {chr(65 + i)}"  # Method A, B, C, ...
        # 生成均匀分布的随机分数
        scores = np.random.uniform(min_score, max_score, n_dimensions)
        # 保留一位小数
        scores = np.round(scores, 1).tolist()
        data[method_name] = scores
    
    return data


# ============================================================================
# 主程序入口 - 测试代码
# ============================================================================

if __name__ == "__main__":
    # ========================================================================
    # 测试 1: 6 个维度的标准雷达图（默认情况）
    # ========================================================================

    print("=" * 60)
    print("测试 1: 6 个维度的雷达图")
    print("=" * 60)

    # 注意：以下维度名称仅为示例，实际使用时请替换为您的业务相关维度
    # 维度名称支持使用 '\n' 进行多行显示
    test_dimensions_6 = [
        "Dimension\n1",
        "Dimension 2",
        "Dimension\n3",
        "Dimension 4",
        "Dimension\n5",
        "Dimension 6"
    ]

    # 生成随机测试数据（6 个维度）
    test_data_6 = generate_test_data(
        n_methods=5,
        n_dimensions=6,
        score_range=(1, 4),
        method_prefix="Method",
        random_seed=42
    )

    # 打印测试数据
    print("生成的测试数据:")
    for method, scores in test_data_6.items():
        print(f"  {method}: {scores}")
    print()

    # 设置保存路径
    output_dir = os.path.join(os.path.dirname(__file__), "output")
    output_path_6 = os.path.join(output_dir, "radar_chart_6dim.png")

    try:
        # 调用绘图函数（6 个维度）
        fig, ax = plot_radar_chart_average_rank(
            data=test_data_6,
            dimensions=test_dimensions_6,
            title="Average Rank (Lower is Better) - 6 Dimensions",
            save_path=output_path_6,
            figsize=(10, 10),
            line_width=2.5,
            alpha_fill=0.15,
            alpha_line=0.9,
            show_legend=True,
            legend_ncol=3,
            y_max=4.5,
            y_ticks=[1, 2, 3, 4],
            grid_alpha=0.25,
            grid_linewidth=1.5,       # 加粗的网格线
            radial_grid_linewidth=1.0,  # 加粗的径向轴线
            dpi=300
        )
        print(f"6 维度雷达图已保存至：{output_path_6}")

    except Exception as e:
        print(f"错误：{e}")
        raise e

    # ========================================================================
    # 测试 2: 5 个维度的雷达图（验证通用性）
    # ========================================================================

    print()
    print("=" * 60)
    print("测试 2: 5 个维度的雷达图（验证通用性）")
    print("=" * 60)

    test_dimensions_5 = [
        "Dim\n1",
        "Dim 2",
        "Dim\n3",
        "Dim 4",
        "Dim 5"
    ]

    test_data_5 = generate_test_data(
        n_methods=4,
        n_dimensions=5,
        score_range=(1, 4),
        method_prefix="Method",
        random_seed=123
    )

    print("生成的测试数据:")
    for method, scores in test_data_5.items():
        print(f"  {method}: {scores}")
    print()

    output_path_5 = os.path.join(output_dir, "radar_chart_5dim.png")

    try:
        fig, ax = plot_radar_chart_average_rank(
            data=test_data_5,
            dimensions=test_dimensions_5,
            title="Average Rank (Lower is Better) - 5 Dimensions",
            save_path=output_path_5,
            figsize=(10, 10),
            line_width=2.5,
            alpha_fill=0.15,
            alpha_line=0.9,
            show_legend=True,
            legend_ncol=2,
            y_max=4.5,
            y_ticks=[1, 2, 3, 4],
            grid_alpha=0.25,
            grid_linewidth=1.5,
            radial_grid_linewidth=1.0,
            dpi=300
        )
        print(f"5 维度雷达图已保存至：{output_path_5}")

    except Exception as e:
        print(f"错误：{e}")
        raise e

    # ========================================================================
    # 测试 3: 8 个维度的雷达图（验证更多维度的情况）
    # ========================================================================

    print()
    print("=" * 60)
    print("测试 3: 8 个维度的雷达图（验证通用性）")
    print("=" * 60)

    test_dimensions_8 = [
        "D1", "D2", "D3", "D4",
        "D5", "D6", "D7", "D8"
    ]

    test_data_8 = generate_test_data(
        n_methods=3,
        n_dimensions=8,
        score_range=(1, 5),
        method_prefix="Method",
        random_seed=456
    )

    print("生成的测试数据:")
    for method, scores in test_data_8.items():
        print(f"  {method}: {scores}")
    print()

    output_path_8 = os.path.join(output_dir, "radar_chart_8dim.png")

    try:
        fig, ax = plot_radar_chart_average_rank(
            data=test_data_8,
            dimensions=test_dimensions_8,
            title="Average Rank (Lower is Better) - 8 Dimensions",
            save_path=output_path_8,
            figsize=(10, 10),
            line_width=2.5,
            alpha_fill=0.15,
            alpha_line=0.9,
            show_legend=True,
            legend_ncol=3,
            y_max=5.5,
            y_ticks=[1, 2, 3, 4, 5],
            grid_alpha=0.25,
            grid_linewidth=1.5,
            radial_grid_linewidth=1.0,
            dpi=300
        )
        print(f"8 维度雷达图已保存至：{output_path_8}")

    except Exception as e:
        print(f"错误：{e}")
        raise e

    # ========================================================================
    # 完成所有测试
    # ========================================================================

    print()
    print("=" * 60)
    print("所有测试完成!")
    print("=" * 60)
    print(f"\n生成的图片文件:")
    print(f"  1. {output_path_6} (6 个维度)")
    print(f"  2. {output_path_5} (5 个维度)")
    print(f"  3. {output_path_8} (8 个维度)")
    print()

    # 打开第一个图片（6 维度）进行预览
    print("正在打开 6 维度雷达图预览...")
    import subprocess
    import platform

    system = platform.system()
    try:
        if system == "Darwin":  # macOS
            subprocess.run(["open", output_path_6], check=True)
        elif system == "Windows":
            subprocess.run(["start", output_path_6], shell=True, check=True)
        elif system == "Linux":
            subprocess.run(["xdg-open", output_path_6], check=True)
        else:
            print(f"不支持的操作系统：{system}，请手动打开图片")
    except Exception as e:
        print(f"打开图片失败：{e}")
        print(f"请手动打开：{output_path_6}")
